import com.amazonaws.services.sqs.AmazonSQS;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kyleolivo' at '9/25/16 12:25 PM' with Gradle 3.1
 *
 * @author kyleolivo, @date 9/25/16 12:25 PM
 */
public class Main {
    public static void main(String[] args) {
        AmazonSQS amazonSQS = null;
        System.out.println("Hello " + amazonSQS);
    }
}
