import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kyleolivo' at '9/25/16 12:25 PM' with Gradle 3.1
 *
 * @author kyleolivo, @date 9/25/16 12:25 PM
 */
public class MainTest {
    @Test public void testSomething() {
        assertTrue(true);
    }
}
